import UIKit

struct StringConstants {
    static let kLblPersonality: String = "Personality"
    static let kLblTtMmYy: String = "tt/mm/yy"
    static let k: String = ""
    static let kLblEditPhoto: String = "Edit Photo"
    static let kLblLastName2: String = "Last Name"
    static let kLblYourEmail: String = "Your Email"
    static let kLblNext: String = "Next"
    static let kLblIndonesian: String = "Indonesian|"
    static let kLblEnglish: String = "English"
    static let kLblAdalahalcana: String = "AdalahAlcana|"
    static let kLblAdalah: String = "Adalah"
    static let kLblIndonesian2: String = "Indonesian"
    static let kMsgDonTHaveAnAccount: String = "Don’t have an account?"
    static let kLblDateOfBirth: String = "Date of birth"
    static let kLblFirstName: String = "First name"
    static let kMsgAlreadyHaveAn: String = "Already have an account?"
    static let kLblCountry: String = "Country"
    static let kMsgLoremIpsumDolor2: String =
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla fermentum netus amet risus commodo amet vulputate tellus. Et quis ornare sed diam in. Id nibh mattis quis fermentum non malesuada. Vel ullamcorper lacus, mollis pellentesque egestas aliquet aliquam. Risus lorem velit, nunc id ornare diam. Odio diam egestas vulputate tristique mi aliquam eget. Feugiat mi sed semper faucibus tellus aliquam nulla ullamcorper arcu. Est in risus pulvinar arcu pretium dui eget pretium. Nunc, sed scelerisque id varius.\nVulputate vel aliquam suscipit vitae, nullam pretium. Ut sed elementum eget id pellentesque. Odio placerat faucibus purus rhoncus, pharetra commodo. Augue a duis vitae tempor lobortis. Aliquam nunc amet fermentum, aliquet elementum ac neque, convallis. Fames nulla ornare diam odio enim. Enim, pellentesque "
    static let kLblFirstName2: String = "First Name"
    static let kLblEmail2: String = "Email"
    static let kLblEMail: String = "E-mail"
    static let kLblToday: String = "Today"
    static let kLbl28May2002: String = "28 May 2002|"
    static let kLblLogOut: String = "Log Out"
    static let kLblSetting: String = "Setting"
    static let kMsgHelpingOthersMeans: String = "Helping others means helping yourself. "
    static let kMsgMakeAWishList: String = "Make a wish list"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kMsgOurCommunityIs: String =
        "our community is ready to help you to join our best platform"
    static let kLblSignUp: String = "Sign Up"
    static let kMsgLoremIpsumDolor: String = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    static let kLblChangeSave: String = "Change save"
    static let kMsgForgotPassword: String = "Forgot Password?"
    static let kMsgIfYouAreAlways: String = "If you are always helping others you are helping yourself too"
    static let kLblHobby: String = "Hobby"
    static let kLblUsername: String = "UserName"
    static let kMsgResearchProduct: String = "Research Product"
    static let kLblAttachments: String = "Attachments"
    static let kLblTaskTodo: String = "Task todo"
    static let kLblSave: String = "Save"
    static let kLbl02April2021: String = "02 April 2021"
    static let kMsgTermsAndConditions: String = "Terms and Conditions"
    static let kMsgYourSettingsSo: String = "Your settings so that we are comfortable"
    static let kLblDate: String = "Date"
    static let kLblFourta: String = "Fourta|"
    static let kLblStart: String = "Start"
    static let kMsgWhenCommunityComes: String = "When community comes unity"
    static let kMsgJoined6MonthAgo: String = "Joined 6 Month Ago"
    static let kLblLastName: String = "Last name"
    static let kLblMaximum10Mb: String = "maximum 10 mb"
    static let kLblWorkTodayS2: String = "Work Today’s"
    static let kLblLogin: String = "Login"
    static let kLblSleep: String = "Sleep|"
    static let kLblAlcanasatre: String = "Alcanasatre"
    static let kMsgCreateActionMobile: String = "Create Action Mobile"
    static let kHttpFail: String = "HTTP request failed"
    static let kLblForgotPassword: String = "Forgot Password"
    static let kMsgMakeYourJobEasier: String = "Make your job easier with our reminders"
    static let kLblPassword: String = "Password"
    static let kMsgOurCommunityIs3: String =
        "Our community is your community too so let's strengthen our community together"
    static let kLblSettings: String = "Settings"
    static let kLblSignup2: String = "SignUp"
    static let kMsgOurCommunityIs2: String =
        "Our community is always there 24 hours if you need it, don't hesitate to join"
    static let kMsgThisIsYourCommunity: String = "this is your community, help them to grow more"
    static let kLblWorkTodayS: String = "Work Today's"
    static let kLblLanguage: String = "Language"
    static let kLblGetInThrough: String = "Get in through"
    static let kMsgCreateActionPlan: String = "Create Action Plan"
    static let kMsgWelcomeToOurCommunity: String = "Welcome to our community"
    static let kInvalidUrl: String = "Invalid URL"
}
